//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang_DoAn_
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienTheSanPham
    {
        public int ID { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string Size { get; set; }
        public string Mau { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
